 with Q1 as (
 	select prod as PRODUCT, month as MONTH,sum(quant) as SUM_QUANT
 	from sales
 	group by PRODUCT,MONTH
	order by MONTH
 ),
 Q2 as (
 	select MONTH,max(SUM_QUANT) as MOST_POPULAR_QUANT, min(SUM_QUANT) as LEAST_POPULAR_QUANT
 	from Q1
 	group by MONTH	
 ),
Q3 as (
 	select Q1.MONTH, Q1.PRODUCT as MOST_POPULAR_PRODUCT, Q2.MOST_POPULAR_QUANT
 	from Q1,Q2
 	where Q1.MONTH=Q2.MONTH and Q1.SUM_QUANT =Q2.MOST_POPULAR_QUANT
 )
select Q3.MONTH,Q3.MOST_POPULAR_PRODUCT,Q3.MOST_POPULAR_QUANT, Q1.PRODUCT as LEAST_POPULAR_PRODUCT, Q2.LEAST_POPULAR_QUANT
from Q1,Q2,Q3
where Q2.MONTH = Q3.MONTH and Q1.SUM_QUANT =Q2.LEAST_POPULAR_QUANT
